### ISSUE TITLE
when giving input file size >1mb it just keeps on computing for a long time without giving output

### ISSUE THREAD

**Issue by richursa** [keith-daigle/cuda-bwt#1]

**Comment by keith-daigle** [comment]
I'm not sure what the issue is but I've definitely tested it on input sizes larger than 1MB.  In fact, doing this calculation on a GPU doesn't have much benefit until the block sizes start to be larger than a CPUs cache.  Depending on the input it can take longer to run than other times, you may want to take a look at the poster.pdf which is included to see how I tested it previously and get a feel for the runtime.  For sure this code still has a degenerate case where if the input is a long string of the same byte it's going to be painfully slow to sort.  I haven't touched this code in like 6 years, so the rot here is probably pretty heavy, too.

**Comment by richursa** [comment]
> For sure this code still has a degenerate case where if the input is a long string of the same byte it's going to be painfully slow to sort.
got it , this was the case. Great Work by the way :+1:
